import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';

class DownloadService {
  static Future<String?> downloadFile({
    required String url,
    required String fileName,
    Function(double)? onProgress,
  }) async {
    try {
      debugPrint('[Download] Starting download: $url');
      
      // Get download directory
      Directory? directory;
      if (Platform.isAndroid) {
        // Try to use Downloads folder
        directory = Directory('/storage/emulated/0/Download');
        if (!await directory.exists()) {
          directory = await getExternalStorageDirectory();
        }
      } else {
        directory = await getApplicationDocumentsDirectory();
      }
      
      if (directory == null) {
        throw Exception('Could not access storage');
      }
      
      // Create Lumina AI folder
      final luminaDir = Directory('${directory.path}/LuminaAI');
      if (!await luminaDir.exists()) {
        await luminaDir.create(recursive: true);
      }
      
      final filePath = '${luminaDir.path}/$fileName';
      final file = File(filePath);
      
      // Download file
      final request = http.Request('GET', Uri.parse(url));
      final response = await http.Client().send(request);
      
      final totalBytes = response.contentLength ?? 0;
      int receivedBytes = 0;
      
      final sink = file.openWrite();
      
      await response.stream.listen(
        (List<int> chunk) {
          sink.add(chunk);
          receivedBytes += chunk.length;
          if (totalBytes > 0 && onProgress != null) {
            onProgress(receivedBytes / totalBytes);
          }
        },
        onDone: () async {
          await sink.close();
        },
        onError: (e) {
          sink.close();
          throw e;
        },
        cancelOnError: true,
      ).asFuture();
      
      await sink.close();
      
      debugPrint('[Download] Saved to: $filePath');
      return filePath;
    } catch (e) {
      debugPrint('[Download] Error: $e');
      return null;
    }
  }
  
  static Future<String?> downloadMusic({
    required String url,
    required String title,
    Function(double)? onProgress,
  }) async {
    // Sanitize filename
    final safeName = title
        .replaceAll(RegExp(r'[<>:"/\\|?*]'), '')
        .replaceAll(' ', '_')
        .trim();
    final fileName = '${safeName}_${DateTime.now().millisecondsSinceEpoch}.mp3';
    
    return downloadFile(
      url: url,
      fileName: fileName,
      onProgress: onProgress,
    );
  }
  
  static Future<String?> downloadLyrics({
    required String lyrics,
    required String title,
    String? artist,
    String? style,
    String? year,
  }) async {
    try {
      Directory? directory;
      if (Platform.isAndroid) {
        directory = Directory('/storage/emulated/0/Download');
        if (!await directory.exists()) {
          directory = await getExternalStorageDirectory();
        }
      } else {
        directory = await getApplicationDocumentsDirectory();
      }
      
      if (directory == null) {
        throw Exception('Could not access storage');
      }
      
      final luminaDir = Directory('${directory.path}/LuminaAI');
      if (!await luminaDir.exists()) {
        await luminaDir.create(recursive: true);
      }
      
      final safeName = title
          .replaceAll(RegExp(r'[<>:"/\\|?*]'), '')
          .replaceAll(' ', '_')
          .trim();
      final fileName = '${safeName}_lyrics.txt';
      final filePath = '${luminaDir.path}/$fileName';
      
      final content = '''
$title
${artist ?? 'Lumina AI'} • ${style ?? 'AI Music'} • ${year ?? DateTime.now().year}
${'=' * 50}

$lyrics

---
Generated by Lumina AI
https://luminaai.zesbe.my.id
''';
      
      final file = File(filePath);
      await file.writeAsString(content);
      
      debugPrint('[Download] Lyrics saved to: $filePath');
      return filePath;
    } catch (e) {
      debugPrint('[Download] Error saving lyrics: $e');
      return null;
    }
  }
}
